### ISSUE TITLE
LSP-copilot options not available in command palette

### ISSUE THREAD

**Issue by beckyjackson** [TerminalFi/LSP-copilot#152] opened 2024-05-14 17:08 UTC
Following the setup instructions, I have installed LSP and LSP-copilot from Package Control, then restarted Sublime. When I open the command palette, I do not see any LSP options. Typing LSP, I can only see the Preferences:

<img width="624" alt="Screen Shot 2024-05-14 at 10 07 21 AM" src="https://github.com/TerminalFi/LSP-copilot/assets/16750150/0134c0ac-c43a-412e-9cf9-437278dc8110">

I am on Sublime build 4169 (latest).

**Comment by jfcherng** [comment] 2024-05-14 17:15
Do LSP-"pyright" work for you?

**Comment by beckyjackson** [comment] 2024-05-14 17:23
I just installed it to see if something would pop up in command palette, I haven't actually set it up at all. Just trying to get LSP-copilot to show up.

**Comment by jfcherng** [comment] 2024-05-14 17:36
I would like to say "run LSP: Troubleshooting" for LSP-copilot but it seems not even LSP is working from your screenshot.

**Comment by jfcherng** [comment] 2024-05-14 17:37
Please provide error message in ST's console.

**Comment by beckyjackson** [comment] 2024-05-14 17:44
No error messages are showing in the console.

**Comment by jfcherng** [comment] 2024-05-14 17:58
And neither there is `LSP: Troubleshooting`?

**Comment by jfcherng** [comment] 2024-05-14 18:18
Mind providing the whole ST console message after just starting up?

**Comment by beckyjackson** [comment] 2024-05-14 18:30
Ah, apologies, there is an error message if I force Sublime to open the console at startup, it just wasn't showing if I opened the console later:
```
reloading plugin LSP-copilot.boot
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP-copilot.sublime-package/boot.py", line 15, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP-copilot.sublime-package/plugin/__init__.py", line 3, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP-copilot.sublime-package/plugin/commands.py", line 9, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/__init__.py", line 12, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 2, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/diagnostics_manager.py", line 2, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/settings.py", line 3, in <module>
  File "/Users/rjackson/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 10, in <module>
ModuleNotFoundError: No module named 'wcmatch'
```

**Comment by jfcherng** [comment] 2024-05-14 18:42
Did you override `channels` in `Package Control`'s plugin settings?

**Comment by jfcherng** [comment] 2024-05-14 18:50
Another thing to make sure is that you are using Package Control v4. But since it has been released for quite a while, it's unlikely the cause.

**Comment by beckyjackson** [comment] 2024-05-15 14:35
Thanks for the pointer - I checked the Package Control settings and saw that the `channels` value had been overriden, and I was missing:
> channel_v4 for python 3.8 compatible libraries 

I removed LSP and LSP-copilot, enabled the `https://packagecontrol.github.io/channel/channel_v4.json` channel, and reinstalled both LSP and LSP-copilot. Upon restarting Sublime, I see this in the console:

```
✈ Copilot has been signed in and authorized.
```

**Comment by jfcherng** [comment] 2024-05-15 14:39
Closed as resolved.

**Closed by jfcherng** 2024-05-15 14:39 UTC
