### ISSUE TITLE
Stopped working entirely

### ISSUE THREAD

**Issue by Gabriel-p** [TerminalFi/LSP-copilot#225] opened 2024-12-21 13:40 UTC
A few days ago (maybe yesterday?) I noticed this plugin just stopped working entirely. Absolutely nothing works. I tried uninstalling and installing back, no changes.

I can Sign out (apparently), but there's no 'Sign in' command shown in the command palette.

These are the only messages I see in the console:

```
LSP: LSP-copilot: Supported execute commands: ['github.copilot.didAcceptCompletionItem', 'github.copilot.didAcceptPanelCompletionItem']
LSP-copilot: INFO: [certificates] Removed 1 expired certificates
LSP-copilot: INFO: [lsp] GitHub Copilot Language Server 1.236.0 initialized
LSP-copilot: WARNING: [lsp] Invalid telemetry setting: Expected object
LSP-copilot: WARNING: [lsp] Invalid  setting: Expected all values to match
LSP-copilot: WARNING: [lsp] Invalid telemetry setting: Expected object
LSP-copilot: WARNING: [lsp] Invalid  setting: Expected all values to match
```

It also blocks `LSP-pyright` so maybe there's something broken with LSP?

**Comment by jfcherng** [comment] 2024-12-21 14:13
I didn't notice anything weird at this moment.

**Comment by jfcherng** [comment] 2024-12-23 05:13
You may try to revert to https://github.com/TerminalFi/LSP-copilot/releases/tag/v0.3.2 to check whether it's caused by a recent update.

**Comment by TerminalFi** [comment] 2024-12-23 14:41
@jfcherng `telemetry` changes

```
telemetry: T.Optional(T.Object({
			telemetryLevel: T.Optional(T.String())
		}
```

`null` or `all`

**Comment by TerminalFi** [comment] 2024-12-23 15:01
@jfcherng We should probably add all skills to the ignoreSkills array unless we know how to supprot them.

```
'current-editor'

'project-labels'

'recent-files'

'git-metadata'

'problems-in-active-document'

```

We also should test these before release

**Comment by TerminalFi** [comment] 2024-12-23 15:47
> A few days ago (maybe yesterday?) I noticed this plugin just stopped working entirely. Absolutely nothing works. I tried uninstalling and installing back, no changes.
> 
> I can Sign out (apparently), but there's no 'Sign in' command shown in the command palette.
> 
> These are the only messages I see in the console:
> 
> ```
> LSP: LSP-copilot: Supported execute commands: ['github.copilot.didAcceptCompletionItem', 'github.copilot.didAcceptPanelCompletionItem']
> LSP-copilot: INFO: [certificates] Removed 1 expired certificates
> LSP-copilot: INFO: [lsp] GitHub Copilot Language Server 1.236.0 initialized
> LSP-copilot: WARNING: [lsp] Invalid telemetry setting: Expected object
> LSP-copilot: WARNING: [lsp] Invalid  setting: Expected all values to match
> LSP-copilot: WARNING: [lsp] Invalid telemetry setting: Expected object
> LSP-copilot: WARNING: [lsp] Invalid  setting: Expected all values to match
> ```
> 
> It also blocks `LSP-pyright` so maybe there's something broken with LSP?

Merged. Will be released shortly

**Closed by TerminalFi** 2024-12-23 15:47 UTC
Labels: bug
